import type { Metadata } from "next"
import { ProductProvider } from "@/app/provider/ProductProvider"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body
        className={`selection:bg-black selection:text-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductProvider>{children}</ProductProvider>
      </body>
    </html>
  )
}
