import { Sidebar } from "@/app/components/shared/Sidebar"
import { Topbar } from "@/app/components/shared/Topbar"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="min-h-screen bg-primary-50 text-neutral-900">
      <div className="flex min-h-screen">
        <Sidebar />

        <section className="flex min-w-0 flex-1 flex-col">
          <Topbar />

          <main className="px-7 py-7">{children}</main>
        </section>
      </div>
    </div>
  )
}
